stages:
  - build


build:
  image: docker:stable
  tags: 
    - nv-ml-example-model
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_USER
    - echo $NV_STORAGE_URI
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE --build-arg secret_key=$CI_JOB_TOKEN --build-arg nv_storage_uri=$NV_STORAGE_URI --build-arg version=$CI_COMMIT_TAG .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

  only:
    - tags

